modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "ALLTHEMONS LICENSE v3.2"

[[mods]]
modId = "zatm_x_msd"
version = "${version}"
displayName = "ATMxMSD"
authors = "Lvantic, YajatKaul"
description = '''
ATM x MSD Version 4.0
by Lvnatic and many others!
'''
logoFile = "/icon.png"

[[dependencies.zatm_x_msd]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zatm_x_msd]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zatm_x_msd]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.zatm_x_msd]]
modId = "cobblemon"
type = "required"
versionRange = "[1.8.0, )"
ordering = "AFTER"
side = "BOTH"

[[dependencies.zatm_x_msd]]
modId = "mega_showdown"
type = "required"
versionRange = "[1.1.2+1.8+1.21.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.zatm_x_msd]]
modId = "accessories"
type = "required"
versionRange = "[1.1.0-beta.52+1.21.1, )"
ordering = "AFTER"
side = "BOTH"