modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "ALLTHEMONS LICENSE v3.2"

[[mods]]
modId = "z_atm_x_msd"
version = "4.1"
displayName = "Cobblemon: ATM x MSD"
authors = "Lvantic
description = '''
ATM x MSD Version 4.1
by Lvnatic and many others!
'''
logoFile = "/icon.png"

[[dependencies.z_atm_x_msd]]
modId = "cobblemon"
type = "required"
reason = "You're missing like the most important mod for this to work. Install/Update it!"
versionRange = "[1.8.1, )"
ordering = "AFTER"
side = "BOTH"

[[dependencies.z_atm_x_msd]]
modId = "mega_showdown"
type = "required"
reason = "You're missing like the second most important mod for this to work. Install/Update it!"
versionRange = "[>=1.2.0+1.8.1+1.21.1-release,)"
ordering = "AFTER"
side = "BOTH"